
server:
  port: 8281
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://localhost:9999"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/ms-customer/**
          filters:
            - RewritePath=/ms-customer/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/